openapi: 3.0.0
info:
  title: URL Shortener
  description: URL Shortener Demo
  version: 1.0.0
servers:
  - url: http://localhost:3140/v1/api
    description: Local server for testing
  - url: https://url-shortner-js93.onrender.com/v1/api
    description: Production Server
components:
  securitySchemes:
    Bearer:
      type: apiKey
      scheme: apiKey
      name: X-Authorization
      in: header
      description: >
        Note: Login to get your JWT token first, then enter "Bearer <JWT Token>" below, e.g., Bearer 123456abcdef.

paths:
  /shorten:
    post:
      tags:
        - Shorten
      summary: Shorten URL
      description: Endpoint to shorten URLs
      security:
        - Bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longUrl:
                  type: string
                  format: uri
                alias:
                  type: string
                topic:
                  type: string
              example:
                longUrl: "http://www.example.com"
                alias: "Test"
                topic: "Test"
      responses:
        "200":
          description: Successfully shortened URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      shortUrl:
                        type: string
                example:
                  message: Success
                  data:
                    shortUrl: "http://localhost:4321/v1/user/shorten/5f3b1"
        "500":
          description: Internal server error

  /shorten/{alias}:
    get:
      tags:
        - Shorten
      summary: Get Shorten URL By Alias
      description: Endpoint to get shorten URLs
      security:
        - Bearer: []
      parameters:
        - in: path
          name: alias
          schema:
            type: string
            required: true
      responses:
        "200":
          description: Successfully shortened URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      shortUrl:
                        type: string
                example:
                  message: Success
                  data:
                    shortUrl: "http://localhost:4321/v1/user/shorten/5f3b1"
        "500":
          description: Internal server error
  /analytics/overall:
    get:
      tags:
        - Shorten
      summary: Get Overall Shorten URL 
      description: Endpoint to get overall shorten URLs analysis
      security:
        - Bearer: []
      responses:
        "200":
          description: Successfully shortened URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      shortUrl:
                        type: string
                example:
                  message: Success
                  data:
                    shortUrl: "http://localhost:4321/v1/user/shorten/5f3b1"
        "500":
          description: Internal server error
  /analytics/{alias}:
    get:
      tags:
        - Shorten
      summary: Get Analytics Shorten URL By Alias
      description: Endpoint to get shorten URLs analysis by alias
      security:
        - Bearer: []
      parameters:
        - in: path
          name: alias
          schema:
            type: string
            required: true
      responses:
        "200":
          description: Successfully shortened URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      shortUrl:
                        type: string
                example:
                  message: Success
                  data:
                    shortUrl: "http://localhost:4321/v1/user/shorten/5f3b1"
        "500":
          description: Internal server error
  /analytics/topic/{topic}:
    get:
      tags:
        - Shorten
      summary: Get Analytics Shorten URL By topic
      description: Endpoint to get shorten URLs analysis by topic
      security:
        - Bearer: []
      parameters:
        - in: path
          name: topic
          schema:
            type: string
            required: true
      responses:
        "200":
          description: Successfully shortened URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      shortUrl:
                        type: string
                example:
                  message: Success
                  data:
                    shortUrl: "http://localhost:4321/v1/user/shorten/5f3b1"
        "500":
          description: Internal server error

